name: marvelapp
description: A project to consume the marvel api.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  core: 
    path: ./packages/core

  flutter:
    sdk: flutter 

  flutter_dotenv: ^5.0.2
  
  flutter_localizations:
    sdk: flutter

  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.6.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/.env