name: marvelapp
description: A project to consume the marvel api.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  core:
    path: ./packages/core
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.2
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.0+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  lint: ^1.6.0
  mockito: ^5.0.16

flutter_app_name:
  name: "Marvel"

flutter_icons:
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  android: true
  ios: true
  web: true

flutter_native_splash:
  fullscreen: true
  android: true
  ios: true
  web: true
  color: "#e1f5fe"
  # background_image: "assets/background.png"
  # image: assets/logo_lockup_flutter_vertical.png
  color_dark: "#042a49"
  # background_image_dark: "assets/dark-background.png"
  # image_dark: assets/logo_lockup_flutter_vertical_wht.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/.env
